[package]
name = "aes-keywrap-rs"
version = "0.1.0"
authors = ["hwiorn (Tim Lee) <hwiorn@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.2"
crypto2 = "0.1.1"